version: '3.7'

services:
  mission6-middleware:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/scr/app/node_modules
    container_name: mission6-middleware
    expose:
      - '8080'
    ports:
      - 8080:8080
    command: npm run dev