version: '3.8'
name: pbtech
services:
  middleware:
    container_name: middleware
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: missionnick/mission6-middleware
    expose:
      - '8080'
    ports:
    - 8080:8080
    networks:
      - pbtech
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  pbtech:
